@startuml

object "Instructor1: Instructor" as Instructor1 {
    firstName = "John"
    lastName = "Doe"
    officeNumber = "7-7777"
}

object "Textbook1: Textbook" as Textbook1 {
    title = "Data Structure & Algorithms in Java"
    author = "Robert Lafore"
    publisher = "Pearson"
}

object "Course1: Course" as course1 {
    courseName = "Java Programming"
    instructor = instructor1
    textbook = textbook1
}

course1 o-- Instructor1
course1 o-- Textbook1
@enduml
